### PR TITLE
Shrink Empty Cards

### PR DESCRIPTION
**Pull request by Stereopoly**
* Shrink empty cards and fitness view
* Center on Berkeley without animation (unrelated)

Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-05 at 15 49 49
Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-05 at 15 49 51

### CODE REVIEW

**Review by KevWho — APPROVED** [review]
Nice. More of a design question, but what do you think about adding a label indicating that no classes / events are found?

**Review by huangshawn1 — CHANGES_REQUESTED** [review]
design said to add some sort of phrase indicating nothing is available instead of just a shrunk card.
see: https://asucocto.slack.com/archives/CNUGAMUAG/p1598738136002000
other than that looks good

**Comment by Stereopoly** [comment]
* Added text option to MissingDataView

**Comment by Stereopoly** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-12 at 15 19 54
Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-12 at 15 19 56

**Review by huangshawn1 — APPROVED** [review]

**Pull request merged**
